/* eslint-disable no-await-in-loop */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function batchPromises<T>(items: T[], batchSize: number, fn: (item: T) => Promise<any>) {
  for (let i = 0; i < items.length; i += batchSize) {
    const batch = items.slice(i, i + batchSize);
    await Promise.all(batch.map(fn));
  }
}

async function main() {
  const contestants = [
    {
      number: '001',
      name: '박시진',
      difficulty: 'D1',
      gender: 'Men',
    },
    {
      number: '002',
      name: '박철우',
      difficulty: 'D1',
      gender: 'Men',
    },
    {
      number: '003',
      name: '김우영',
      difficulty: 'D1',
      gender: 'Men',
    },
    {
      number: '004',
      name: '이장성',
      difficulty: 'D1',
      gender: 'Men',
    },
    {
      number: '005',
      name: '성영기',
      difficulty: 'D1',
      gender: 'Men',
    },
    {
      number: '006',
      name: '김현',
      difficulty: 'D1',
      gender: 'Men',
    },
    {
      number: '007',
      name: '이호준',
      difficulty: 'D1',
      gender: 'Men',
    },
    {
      number: '008',
      name: '최원철',
      difficulty: 'D1',
      gender: 'Men',
    },
    {
      number: '009',
      name: '이원석',
      difficulty: 'D1',
      gender: 'Men',
    },
    {
      number: '010',
      name: '김세정',
      difficulty: 'D1',
      gender: 'Men',
    },
    {
      number: '011',
      name: '목정민',
      difficulty: 'D1',
      gender: 'Men',
    },
    {
      number: '012',
      name: '윤대식',
      difficulty: 'D1',
      gender: 'Men',
    },
    {
      number: '013',
      name: '김대언',
      difficulty: 'D1',
      gender: 'Men',
    },
    {
      number: '014',
      name: '장성욱',
      difficulty: 'D1',
      gender: 'Men',
    },
    {
      number: '015',
      name: '최민건',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '016',
      name: '박부기',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '017',
      name: '주현호',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '018',
      name: '곽민수',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '019',
      name: '송현수',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '020',
      name: '정세원',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '021',
      name: '박우영',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '022',
      name: '이태웅',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '023',
      name: '박형준',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '024',
      name: '최영학',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '025',
      name: '허세민',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '026',
      name: '방삼혁',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '027',
      name: '장태규',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '028',
      name: '최형진',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '029',
      name: '박재현',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '030',
      name: '이승제',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '031',
      name: '박시우',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '032',
      name: '김민준',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '033',
      name: '이건우',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '034',
      name: '김태영',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '035',
      name: '제현구',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '036',
      name: '박류식',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '037',
      name: '박창현',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '038',
      name: '이상화',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '039',
      name: '이영현',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '040',
      name: '하다경',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '041',
      name: '성재영',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '042',
      name: '조혜진',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '043',
      name: '최연주',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '044',
      name: '임경륜',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '045',
      name: '오재희',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '046',
      name: '고동오',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '047',
      name: '양동빈',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '048',
      name: '채예준',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '049',
      name: '김민성',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '050',
      name: '최일해',
      difficulty: 'D2',
      gender: 'Men',
    },
    {
      number: '051',
      name: '김용한',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '052',
      name: '강도엽',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '053',
      name: '김도균',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '054',
      name: '이호중',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '055',
      name: '정찬영',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '056',
      name: '박성현',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '057',
      name: '배철민',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '058',
      name: '박지원',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '059',
      name: '김현수',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '060',
      name: '성제욱',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '061',
      name: '조재빈',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '062',
      name: '이종연',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '063',
      name: '김기용',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '064',
      name: '서인재',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '065',
      name: '백지원',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '066',
      name: '강승훈',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '067',
      name: '남치현',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '068',
      name: '고동규',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '069',
      name: '김수완',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '070',
      name: '한성현',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '071',
      name: '변진호',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '072',
      name: '정국환',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '073',
      name: '류재상',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '074',
      name: '김태훈',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '075',
      name: '김동현',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '076',
      name: '윤원근',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '077',
      name: '이지현',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '078',
      name: '김효빈',
      difficulty: 'D3',
      gender: 'Men',
    },
    {
      number: '079',
      name: '남수민',
      difficulty: 'D3',
      gender: 'Women',
    },
    {
      number: '080',
      name: '정주현',
      difficulty: 'D3',
      gender: 'Women',
    },
    {
      number: '081',
      name: '예하진',
      difficulty: 'D3',
      gender: 'Women',
    },
    {
      number: '082',
      name: '이주희',
      difficulty: 'D3',
      gender: 'Women',
    },
    {
      number: '083',
      name: '이영광',
      difficulty: 'D3',
      gender: 'Women',
    },
    {
      number: '084',
      name: '윤원준',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '085',
      name: '김태윤',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '086',
      name: '강성원',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '087',
      name: '김지광',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '088',
      name: '김범식',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '089',
      name: '이승호',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '090',
      name: '박일선',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '091',
      name: '이현일',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '092',
      name: '강부현',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '093',
      name: '김종섭',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '094',
      name: '박상현',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '095',
      name: '박주환',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '096',
      name: '천기범',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '097',
      name: '김태현',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '098',
      name: '김지호',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '099',
      name: '주한승',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '100',
      name: '박세현',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '101',
      name: '이민균',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '102',
      name: '유근배',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '103',
      name: '하석현',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '104',
      name: '윤이헌',
      difficulty: 'D4',
      gender: 'Men',
    },
    {
      number: '105',
      name: '이예슬',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '106',
      name: '박주빈',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '107',
      name: '김주은',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '108',
      name: '하문경',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '109',
      name: '민초록',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '110',
      name: '전희윤',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '111',
      name: '김완선',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '112',
      name: '박아현',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '113',
      name: '김향선',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '114',
      name: '차지은',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '115',
      name: '전가을',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '116',
      name: '문지원',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '117',
      name: '조민아',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '118',
      name: '길혜경',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '119',
      name: '김한별',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '120',
      name: '홍주영',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '121',
      name: '이유미',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '122',
      name: '김혜숙',
      difficulty: 'D4',
      gender: 'Women',
    },
    {
      number: '123',
      name: '김형은',
      difficulty: 'D4',
      gender: 'Women',
    },
  ];
  await batchPromises(contestants, 10, async contestant => {
    await prisma.contestant.upsert({
      where: { number: contestant.number },
      update: {},
      create: {
        number: contestant.number,
        name: contestant.name,
        difficulty: contestant.difficulty as 'D1' | 'D2' | 'D3' | 'D4' | 'D5',
        gender: contestant.gender as 'Men' | 'Women',
      },
    });
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async e => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
